<a href="https://colab.research.google.com/github/nsaedae/Colab/blob/main/1_3_PandasTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/02/01
이름 : 김은표
내용 : 파이썬 Pandas 데이터프레임 실습하기
"""

In [ ]:
import pandas as pd

In [ ]:
#데이터프레임 생성
df1 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
df1

df2 = pd.DataFrame({'uid' : ['A101', 'A102', 'A103', 'A104', 'A105'],
                    'name': ['김유신', '김춘추', '장보고', '강감찬', '이순신'],
                    'age' : [21, 25, 31, 27, 35]})
df2

    uid name  age
0  A101  김유신   21
1  A102  김춘추   25
2  A103  장보고   31
3  A104  강감찬   27
4  A105  이순신   35

In [ ]:
#데이터프레임 출력
print(df1[0][0])
print(df1[0][1])
print(df1[1][2])
print(df2['uid'][0])
print(df2['name'][1])

In [ ]:
#구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#데이터 불러오기
df_exam = pd.read_csv('/content/drive/My Drive/Colab Notebooks/file/exam.csv')
df_exam

In [ ]:
#기본 요약 통계
df_exam.describe()

In [ ]:
#상위 5개 미리보기
df_exam.head()

In [ ]:
#하위 5개 미리보기
df_exam.tail()

In [ ]:
#데이터프레임 인덱싱
#loc  - 컬럼명 인덱싱
df1 = df_exam.loc[:, ['math', 'science']]
df1

df2 = df_exam.loc[1:4, ['math', 'english']]
df2

#iloc - 인덱스 번호 인덱싱
df3 = df_exam.iloc[1:5, 2:4]
df3

In [ ]:
#수학점수 60점 이상 데이터프레임 생성
df_math = df_exam[df_exam.math >= 60]
df_math

In [ ]:
#수학점수 내림차순
df_math.sort_values(by='math', ascending=False)

In [ ]:
#영어점수 60 ~ 70, 내림차순 정렬
df_eng = df_exam[(df_exam.english >= 60) & (df_exam.english < 70)].sort_values(by='english', ascending=False)
df_eng

In [ ]:
#파생변수
df_exam['total'] = df_exam.math + df_exam.english + df_exam.science
df_exam

df_exam['mean'] = df_exam.total / 3
df_exam